title: Pierre-Etienne TOULEMONDE
logo: # Mon logo
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Pharmacist & Data scientist, degree in Data science and machine learning science with Datacamp. Previously at       Sant√© Publique France (National Public Health Agency), ANSES (National Food Safety Agency), AP-HP (Paris       Hospitals Public Assistance) and AstraZeneca
  <br><br>
  <a href="https://fr.linkedin.com/in/pierre-etienne-toulemonde/fr" target="_blank">View my Linkedin Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-4PZ4G86YR0

colors:
  crimson: '#900C3F'
