title: Pierre-Etienne TOULEMONDE
logo: # Mon logo
description: >
 ğŸ‘‹ Hi, Iâ€™m Pierre-Etienne, pharmacist and data scientist.

ğŸ‘€ From data visualization with ggplot2 or plotly, RShiny or powerBI to machine learning and deep learning with TensorFlow for example, exploring data to get insights and using models to understand and create the 	world of tomorrow is my passion and occupies all my free time! I code as much in R as in Python, with a small preference for plotly in Python and RShiny in R.
  <br><br>
In my github repository, you will find : 
- My presentation (which you are currently reading),
- The projects I've done in the Projects_done repository,
- My current projects, each in their repository .
Don't hesitate to have a look at the projects I've already done, you'll find viz', deep learning, NLP. I won't say everything to keep the mystery alive! 

The Project_done repository has its own README, to guide you in the theme of the projects, the packages used and the language used.
    
ğŸ’ï¸ I want to give back to the community what it brings me every day, when my code doesn't want to work.

ğŸ“« You can reach me at pierre-etienne.toulemonde@outlook.com, for questions, job offer or proposal for collaboration on a R or python project. 
Working together is always a great opportunity to do great things!
  <br><br>
  
  [My linkedin profile](https://fr.linkedin.com/in/pierre-etienne-toulemonde/fr)
  
theme: jekyll-theme-minimal
google_analytics: G-4PZ4G86YR0
